### ISSUE TITLE
Code Editor

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/design#25]
### Goal

An interactive code editor

### Tasks

- [ ] Based on atom `code-block`
- [ ] [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)
- [ ] Watch for changes and call `hljs.highlight()`
    ```html
    <pre class="code-block malachite hljs language-java"
         contenteditable="true"
         onfocusout="this.removeAttribute('data-highlighted');console.log(document.getSelection());console.log(this); hljs.highlightElement(this)" data-highlighted="yes">
    ```
